FROM crose72/jetson-inference:r32.7.1

ENV DEBIAN_FRONTEND=noninteractive

RUN wget https://cmake.org/files/v3.28/cmake-3.28.0-linux-aarch64.sh && \
    chmod +x cmake-3.28.0-linux-aarch64.sh && \
    ./cmake-3.28.0-linux-aarch64.sh --prefix=/usr/local --exclude-subdir && \
    rm cmake-3.28.0-linux-aarch64.sh 

RUN apt-get update && apt install -y \
    libspdlog-dev \
    libfmt-dev \
    libjsoncpp-dev \
    libarmadillo-dev \
    liblapack-dev \
    libblas-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/pjueon/JetsonGPIO.git && \
    cd JetsonGPIO && \
    mkdir build && cd build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && rm -rf JetsonGPIO

# Copy fake model file so OpenCV build script knows which Jetson to compile for
COPY docker/fake-proc/device-tree/model /opt/device-tree/model

RUN apt-get update && apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev && \
	pkg-config --modversion gstreamer-1.0 && \
    mkdir -p /fake-proc/device-tree && \
    cp /opt/device-tree/model /fake-proc/device-tree/model && \
    git clone https://github.com/crose72/Install-OpenCV-Jetson-Nano.git && \
    cd Install-OpenCV-Jetson-Nano && \
    chmod +x OpenCV-4-10-0-tracking.sh && \
    sed -i 's|/proc/device-tree|/fake-proc/device-tree|g' OpenCV-4-10-0-tracking.sh && \
    sed -i 's/sudo //g' OpenCV-4-10-0-tracking.sh && \
    apt-get update && \
    ./OpenCV-4-10-0-tracking.sh && \
    cd .. && rm -rf Install-OpenCV-Jetson-Nano
